server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /api/ {
      limit_except GET POST PUT DELETE PATCH {
        deny all;
      }
      proxy_pass http://back:3000/;
    }
}
